kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: submariner-k8s-broker-cluster-{{ .ManagedClusterName }}
  namespace: {{ .SubmarinerBrokerNamespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: submariner-k8s-broker-cluster
subjects:
  - kind: ServiceAccount
    name: {{ .ManagedClusterName }}
    namespace: {{ .SubmarinerBrokerNamespace }}
