apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: open-cluster-management:submariner
  namespace: {{ .SubmarinerNamespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: open-cluster-management:submariner
subjects:
- kind: ServiceAccount
  name: open-cluster-management:submariner
