apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: open-cluster-management:submariner
  namespace: {{ .SubmarinerNamespace }}
rules:
# Allow spoke registration agent to get/update coordination.k8s.io/lease
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  resourceNames: ["cluster-lease-{{ .ManagedClusterName }}"]
  verbs: ["get", "update"]
